baseURL = "https://gabac.blog"
languageCode = "en-us"
title = "Great, another blog about coding!"
theme = "athena"


[params]
description = "and that is sarcasm"
dateform = "Jan 2, 2006"
disable_next_prev = true
github_repo = "gabac"
github_username = "rmpato"
