baseURL = "https://gabac.now.sh"
languageCode = "en-us"
title = "Great, another blog about coding!"
theme = "athena"


[params]
description = "mantained by Pato"
dateform = "Jan 2, 2006"
disable_next_prev = true
github_repo = "therepo"
github_username = "rmpato"
