baseURL = "https://gabac.now.sh"
languageCode = "en-us"
title = "Great, another blog about coding!"
theme = "athena"


[params]
description = "mantained by Pato"
dateform = "Nov 28, 2019"
disable_next_prev = true
github_repo = "gabac"
github_username = "rmpato"
